from __future__ import annotations

import sqlite3
import re
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator, Mapping


class DatabaseRow(Mapping[str, Any]):
    def __init__(self, columns: list[str], values: tuple[Any, ...]):
        self._columns = columns
        self._values = values
        self._data = dict(zip(columns, values))

    def __getitem__(self, key: str | int) -> Any:
        return self._values[key] if isinstance(key, int) else self._data[key]

    def __iter__(self):
        return iter(self._data)

    def __len__(self) -> int:
        return len(self._data)


class PostgresCursor:
    def __init__(self, cursor, lastrowid: int | None = None):
        self.cursor = cursor
        self.lastrowid = lastrowid
        self.rowcount = cursor.rowcount

    def _row(self, row):
        if row is None:
            return None
        columns = [item.name for item in self.cursor.description]
        return DatabaseRow(columns, tuple(row))

    def fetchone(self):
        return self._row(self.cursor.fetchone())

    def fetchall(self):
        return [self._row(row) for row in self.cursor.fetchall()]


class PostgresConnection:
    identity_tables = {"memories", "reminders", "expenses", "events", "approvals", "audit_logs", "job_listings", "applications", "application_notes", "follow_ups", "resume_versions", "users"}

    def __init__(self, connection):
        self.connection = connection

    @staticmethod
    def _query(sql: str) -> str:
        sql = sql.replace("datetime('now','-7 days')", "(CURRENT_TIMESTAMP - INTERVAL '7 days')")
        return sql.replace("?", "%s")

    def execute(self, sql: str, params=()):
        query = self._query(sql)
        match = re.match(r"\s*INSERT\s+INTO\s+([a-z_]+)", query, re.I)
        wants_id = bool(match and match.group(1).lower() in self.identity_tables and "RETURNING" not in query.upper())
        if wants_id:
            query = query.rstrip().rstrip(";") + " RETURNING id"
        cursor = self.connection.cursor()
        cursor.execute(query, params)
        lastrowid = None
        if wants_id:
            returned = cursor.fetchone()
            lastrowid = int(returned[0]) if returned else None
        return PostgresCursor(cursor, lastrowid)


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS memories (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, text TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reminders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, task TEXT NOT NULL, due_at TEXT, completed INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS expenses (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, amount DOUBLE PRECISION NOT NULL, category TEXT NOT NULL, note TEXT NOT NULL, occurred_on TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, title TEXT NOT NULL, starts_at TEXT NOT NULL, ends_at TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS approvals (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, tool_name TEXT NOT NULL, summary TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, resolved_at TIMESTAMPTZ, decision_note TEXT, action_payload TEXT);
CREATE TABLE IF NOT EXISTS audit_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, event_type TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id BIGINT, details TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS job_listings (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source TEXT NOT NULL, source_id TEXT NOT NULL, query TEXT NOT NULL, title TEXT NOT NULL, company TEXT, location TEXT, description TEXT, salary_min DOUBLE PRECISION, salary_max DOUBLE PRECISION, redirect_url TEXT, posted_at TEXT, fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(source, source_id));
CREATE TABLE IF NOT EXISTS applications (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, job_listing_id BIGINT NOT NULL REFERENCES job_listings(id), status TEXT NOT NULL DEFAULT 'SAVED', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(sender, job_listing_id));
CREATE TABLE IF NOT EXISTS career_profiles (sender TEXT PRIMARY KEY, resume_text TEXT NOT NULL, skills_json TEXT NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS application_notes (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL REFERENCES applications(id), body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS follow_ups (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, application_id BIGINT NOT NULL REFERENCES applications(id), due_on TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS resume_versions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sender TEXT NOT NULL, label TEXT NOT NULL, resume_text TEXT NOT NULL, skills_json TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS oauth_states (state TEXT PRIMARY KEY, sender TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS oauth_connections (provider TEXT NOT NULL, sender TEXT NOT NULL, encrypted_token TEXT NOT NULL, connected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(provider, sender));
CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_settings (sender TEXT PRIMARY KEY, display_name TEXT NOT NULL DEFAULT 'Syed Saud', target_role TEXT NOT NULL DEFAULT 'Data Engineer', target_location TEXT NOT NULL DEFAULT 'Pune', minimum_fit INTEGER NOT NULL DEFAULT 45, weekly_digest INTEGER NOT NULL DEFAULT 1, follow_up_reminders INTEGER NOT NULL DEFAULT 1, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO schema_migrations(version, name) VALUES (1, 'initial production schema') ON CONFLICT (version) DO NOTHING;
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_notes_application ON application_notes(application_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_follow_ups_application ON follow_ups(application_id, completed, due_on);
CREATE INDEX IF NOT EXISTS idx_resume_versions_sender ON resume_versions(sender, id DESC);
CREATE INDEX IF NOT EXISTS idx_approvals_status_id ON approvals(status, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_job_listings_query ON job_listings(query, id DESC);
CREATE INDEX IF NOT EXISTS idx_applications_sender_status ON applications(sender, status, id DESC);
"""


class Store:
    def __init__(self, path: Path, database_url: str | None = None):
        self.path = path
        self.database_url = database_url

    @contextmanager
    def connection(self) -> Iterator[Any]:
        if self.database_url:
            import psycopg
            raw = psycopg.connect(self.database_url)
            con = PostgresConnection(raw)
            try:
                yield con
                raw.commit()
            except Exception:
                raw.rollback()
                raise
            finally:
                raw.close()
            return
        self.path.parent.mkdir(parents=True, exist_ok=True)
        con = sqlite3.connect(self.path)
        con.row_factory = sqlite3.Row
        try:
            yield con
            con.commit()
        finally:
            con.close()

    def initialize(self) -> None:
        if self.database_url:
            import psycopg
            with psycopg.connect(self.database_url) as con:
                for statement in POSTGRES_SCHEMA.split(";"):
                    if statement.strip():
                        con.execute(statement)
            return
        with self.connection() as con:
            con.executescript(
                """
                CREATE TABLE IF NOT EXISTS schema_migrations (
                  version INTEGER PRIMARY KEY, name TEXT NOT NULL,
                  applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS memories (
                  id INTEGER PRIMARY KEY, sender TEXT NOT NULL, text TEXT NOT NULL,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS reminders (
                  id INTEGER PRIMARY KEY, sender TEXT NOT NULL, task TEXT NOT NULL,
                  due_at TEXT, completed INTEGER NOT NULL DEFAULT 0,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS expenses (
                  id INTEGER PRIMARY KEY, sender TEXT NOT NULL, amount REAL NOT NULL,
                  category TEXT NOT NULL, note TEXT NOT NULL,
                  occurred_on TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS events (
                  id INTEGER PRIMARY KEY, sender TEXT NOT NULL, title TEXT NOT NULL,
                  starts_at TEXT NOT NULL, ends_at TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS approvals (
                  id INTEGER PRIMARY KEY, sender TEXT NOT NULL, tool_name TEXT NOT NULL,
                  summary TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'PENDING',
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  resolved_at TEXT, decision_note TEXT
                );
                CREATE TABLE IF NOT EXISTS audit_logs (
                  id INTEGER PRIMARY KEY,
                  sender TEXT NOT NULL,
                  event_type TEXT NOT NULL,
                  entity_type TEXT NOT NULL,
                  entity_id INTEGER,
                  details TEXT NOT NULL,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS job_listings (
                  id INTEGER PRIMARY KEY,
                  source TEXT NOT NULL,
                  source_id TEXT NOT NULL,
                  query TEXT NOT NULL,
                  title TEXT NOT NULL,
                  company TEXT,
                  location TEXT,
                  description TEXT,
                  salary_min REAL,
                  salary_max REAL,
                  redirect_url TEXT,
                  posted_at TEXT,
                  fetched_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  UNIQUE(source, source_id)
                );
                CREATE TABLE IF NOT EXISTS applications (
                  id INTEGER PRIMARY KEY,
                  sender TEXT NOT NULL,
                  job_listing_id INTEGER NOT NULL,
                  status TEXT NOT NULL DEFAULT 'SAVED',
                  notes TEXT,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  UNIQUE(sender, job_listing_id),
                  FOREIGN KEY(job_listing_id) REFERENCES job_listings(id)
                );
                CREATE TABLE IF NOT EXISTS career_profiles (
                  sender TEXT PRIMARY KEY,
                  resume_text TEXT NOT NULL,
                  skills_json TEXT NOT NULL,
                  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS application_notes (
                  id INTEGER PRIMARY KEY,
                  application_id INTEGER NOT NULL,
                  body TEXT NOT NULL,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  FOREIGN KEY(application_id) REFERENCES applications(id)
                );
                CREATE TABLE IF NOT EXISTS follow_ups (
                  id INTEGER PRIMARY KEY,
                  application_id INTEGER NOT NULL,
                  due_on TEXT NOT NULL,
                  completed INTEGER NOT NULL DEFAULT 0,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  FOREIGN KEY(application_id) REFERENCES applications(id)
                );
                CREATE TABLE IF NOT EXISTS resume_versions (
                  id INTEGER PRIMARY KEY,
                  sender TEXT NOT NULL,
                  label TEXT NOT NULL,
                  resume_text TEXT NOT NULL,
                  skills_json TEXT NOT NULL,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS oauth_states (
                  state TEXT PRIMARY KEY, sender TEXT NOT NULL, expires_at TEXT NOT NULL
                );
                CREATE TABLE IF NOT EXISTS oauth_connections (
                  provider TEXT NOT NULL, sender TEXT NOT NULL, encrypted_token TEXT NOT NULL,
                  connected_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  PRIMARY KEY(provider, sender)
                );
                CREATE TABLE IF NOT EXISTS users (
                  id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL,
                  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE TABLE IF NOT EXISTS user_settings (
                  sender TEXT PRIMARY KEY,
                  display_name TEXT NOT NULL DEFAULT 'Syed Saud',
                  target_role TEXT NOT NULL DEFAULT 'Data Engineer',
                  target_location TEXT NOT NULL DEFAULT 'Pune',
                  minimum_fit INTEGER NOT NULL DEFAULT 45,
                  weekly_digest INTEGER NOT NULL DEFAULT 1,
                  follow_up_reminders INTEGER NOT NULL DEFAULT 1,
                  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                );
                CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
                CREATE INDEX IF NOT EXISTS idx_notes_application ON application_notes(application_id, id DESC);
                CREATE INDEX IF NOT EXISTS idx_follow_ups_application ON follow_ups(application_id, completed, due_on);
                CREATE INDEX IF NOT EXISTS idx_resume_versions_sender ON resume_versions(sender, id DESC);
                CREATE INDEX IF NOT EXISTS idx_approvals_status_id ON approvals(status, id DESC);
                CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id, id DESC);
                CREATE INDEX IF NOT EXISTS idx_job_listings_query ON job_listings(query, id DESC);
                CREATE INDEX IF NOT EXISTS idx_applications_sender_status ON applications(sender, status, id DESC);
                INSERT OR IGNORE INTO schema_migrations(version, name) VALUES (1, 'initial production schema');
                """
            )
            columns = {row["name"] for row in con.execute("PRAGMA table_info(approvals)").fetchall()}
            if "action_payload" not in columns:
                con.execute("ALTER TABLE approvals ADD COLUMN action_payload TEXT")
