import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

const navigate = (page, name) => page.getByRole('navigation', { name: 'Main navigation' }).getByRole('button', { name, exact: true }).click()

async function assertLayout(page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  // Automated Level-A checks supplement keyboard and visual QA, not a full WCAG certification.
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag21a']).analyze()
  expect(result.violations).toEqual([])
}

test('public demo: navigation, filters, copilot, downloads, keyboard and API isolation', async ({ page }) => {
  const apiCalls = []
  const errors = []
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/')) apiCalls.push(request.url()) })
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/demo')
  await expect(page.getByRole('note')).toContainText('100% synthetic sample data')
  await expect(page.getByText('Syed Saud', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Explorer')
  await expect(page.getByRole('heading', { name: 'Your weekly momentum' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Your next actions' })).toBeVisible()
  await page.locator('.next-actions-body > button').first().click()
  await expect(page.getByRole('region', { name: 'Application workspace', exact: true })).toBeVisible()
  await page.getByRole('region', { name: 'Application workspace', exact: true }).press('Escape')
  await navigate(page, 'Overview')
  await expect(page.locator('.career-activity svg circle')).toHaveCount(8)
  await page.getByRole('button', { name: 'View detailed activity trends' }).click()
  await expect(page.getByRole('heading', { name: 'Eight-week activity trends' })).toBeVisible()
  await navigate(page, 'Overview')
  await assertLayout(page)
  await page.getByLabel('Career intelligence query').press('Control+k')
  await expect(page.getByLabel('Career intelligence query')).toBeFocused()
  await page.getByRole('button', { name: 'Run intelligence scan' }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Roles worth')
  await expect(page.getByRole('heading', { level: 1 })).toBeFocused()
  await page.getByRole('combobox', { name: 'Work mode', exact: true }).selectOption('REMOTE')
  await expect(page.locator('.job-card')).toHaveCount(1)
  await page.getByRole('combobox', { name: 'Location', exact: true }).selectOption('Pune')
  await expect(page.getByText('No matching roles in this view.')).toBeVisible()
  await page.getByRole('button', { name: 'Show all opportunities' }).click()
  await expect(page.locator('.job-card')).toHaveCount(6)
  await assertLayout(page)
  await navigate(page, 'Pipeline')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export sample CSV' }).click()
  expect((await download).suggestedFilename()).toBe('jarvis-demo-applications.csv')
  const open = page.getByRole('button', { name: 'Open workspace', exact: true }).first()
  await open.click()
  await expect(page.getByText('RESUME COPILOT', { exact: true })).toBeVisible()
  await expect(page.getByText('INTERVIEW INTELLIGENCE', { exact: true })).toBeVisible()
  await page.getByRole('region', { name: 'Application workspace', exact: true }).press('Escape')
  await expect(open).toBeFocused()
  await navigate(page, 'Action center')
  await expect(page.getByLabel('Recipient email')).toBeDisabled()
  await expect(page.getByLabel('Event title')).toBeDisabled()
  await assertLayout(page)
  await navigate(page, 'Insights & settings')
  await expect(page.getByRole('heading', { name: 'Your next learning priorities' })).toBeVisible()
  await expect(page.locator('.table-scroll tbody tr')).toHaveCount(8)
  await assertLayout(page)
  await navigate(page, 'Project showcase')
  await expect(page.getByRole('link', { name: 'GitHub profile' })).toHaveAttribute('href', 'https://github.com/syedsaud15')
  await expect(page.getByText(/Source repository is private/)).toBeVisible()
  await assertLayout(page)
  await navigate(page, 'Privacy & safety')
  await assertLayout(page)
  expect(apiCalls).toEqual([])
  expect(errors).toEqual([])
})

test('personal synthetic workspace: capture, copilot, notes, stage history and backup', async ({ page, request }) => {
  await request.post('/__test/reset')
  await page.goto('/')
  await expect(page.locator('.next-actions')).toContainText('No pending actions')
  const momentum = await page.locator('.career-activity').boundingBox()
  const actions = await page.locator('.next-actions').boundingBox()
  if (page.viewportSize().width > 800) {
    expect(Math.abs(momentum.y - actions.y)).toBeLessThan(2)
    expect(Math.abs(momentum.width - actions.width)).toBeLessThan(2)
  } else {
    expect(actions.y).toBeGreaterThan(momentum.y + momentum.height)
  }
  await page.locator('.next-actions').getByRole('button', { name: 'Explore opportunities' }).click()
  await page.getByRole('button', { name: 'Capture role', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Captured ✓' })).toBeDisabled()
  await navigate(page, 'Pipeline')
  await page.getByRole('button', { name: 'Mark applied' }).click()
  await expect(page.getByRole('button', { name: 'Move to interview' })).toBeVisible()
  await page.getByRole('button', { name: 'Move to interview' }).click()
  await page.getByRole('button', { name: 'Open workspace', exact: true }).click()
  await expect(page.getByText('RESUME COPILOT', { exact: true })).toBeVisible()
  await expect(page.getByText('Gaps: kafka')).toBeVisible()
  await page.getByLabel('Private note').fill('QA reliability story')
  await page.getByRole('button', { name: 'Add note', exact: true }).click()
  await expect(page.getByText('QA reliability story', { exact: true })).toBeVisible()
  await page.getByLabel('Follow-up date').fill('2030-01-01')
  await page.getByRole('button', { name: 'Schedule follow-up', exact: true }).click()
  await page.getByRole('button', { name: 'Close application workspace' }).click()
  await navigate(page, 'Insights & settings')
  await expect(page.getByRole('heading', { name: 'kafka · 1 role signals' })).toBeVisible()
  await page.getByLabel('Display name').fill('QA Candidate')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByRole('status')).toContainText('Career preferences saved')
  const backup = await request.get('/api/backup/export.json')
  const payload = await backup.json()
  expect(payload.version).toBe(2)
  expect(payload.tables.application_notes[0].body).toBe('QA reliability story')
  expect(payload.tables.follow_ups).toHaveLength(1)
  const history = await (await request.get('/api/analytics/trends')).json()
  expect(history.weeks.at(-1).applied).toBe(1)
  expect(history.weeks.at(-1).interviews).toBe(1)
  await assertLayout(page)
})
